# IPO & ETF Launch Tracker — Data Explorer

Connect to the SQLite database and interactively explore all pipeline tables.  
Run cells top-to-bottom, or jump to any section you need.

In [1]:
import sqlite3
import pandas as pd
from pathlib import Path

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 60)
pd.set_option("display.width", 200)

# Connect to database
DB_PATH = Path("../db/ipo_etf_tracker.db")
assert DB_PATH.exists(), f"Database not found at {DB_PATH.resolve()}. Run 'python main.py --init' first."
conn = sqlite3.connect(str(DB_PATH))
print(f"Connected to {DB_PATH.resolve()}")

tables = [r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()]
print(f"Tables: {tables}")

Connected to C:\Users\vmc30\OneDrive\Desktop\Personal_Repos\IPO_ETF\db\ipo_etf_tracker.db
Tables: ['stock_ipos', 'sqlite_sequence', 'etf_launches', 'filing_events', 'active_securities', 'notifications']

## Stock IPOs Pipeline

All entities from S-1/F-1 filings, tracking from registration through launch.

In [2]:
# All stock IPOs
df_ipos = pd.read_sql_query("SELECT * FROM stock_ipos ORDER BY updated_at DESC", conn)
print(f"Total IPO entities: {len(df_ipos)}")
df_ipos

Total IPO entities: 35

,id,entity_name,ticker,cik,status,form_type,filing_date,effective_date,launch_date,price,exchange,sic_code,edgar_url,created_at,updated_at
0,4,SMX (Security Matters) Public Ltd Co,None,1940674,AMENDED,F-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1940674/00014931...,2026-03-03T00:20:34.813194,2026-03-03T00:21:31.443853
1,35,RMG ML Sports Holdings,None,2104879,FILED,S-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2104879/00012139...,2026-03-03T00:21:24.695910,2026-03-03T00:21:24.695910
2,34,UDynamics Ltd,None,2097903,FILED,F-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2097903/00012139...,2026-03-03T00:21:24.640312,2026-03-03T00:21:24.640312
3,33,Metals Royalty Co Inc.,None,2087398,FILED,F-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2087398/00011046...,2026-03-03T00:21:24.618340,2026-03-03T00:21:24.618340
4,32,APEX Global Solutions Ltd,None,2069858,FILED,F-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2069858/00012139...,2026-03-03T00:21:24.546673,2026-03-03T00:21:24.546673
5,31,TDE GROUP Ltd,None,2053475,FILED,F-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2053475/00018934...,2026-03-03T00:21:24.476671,2026-03-03T00:21:24.476671
6,30,Collab Z Inc.,None,2050338,FILED,S-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2050338/00012139...,2026-03-03T00:21:24.454667,2026-03-03T00:21:24.454667
7,29,BeLive Holdings,None,1982448,FILED,F-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1982448/00014931...,2026-03-03T00:21:23.914265,2026-03-03T00:21:23.914265
8,28,Steakholder Foods Ltd.,None,1828098,FILED,F-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1828098/00012139...,2026-03-03T00:21:22.405219,2026-03-03T00:21:22.405219
9,27,"Modular Medical, Inc.",None,1074871,FILED,S-1,2026-02-27,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1074871/00012139...,2026-03-03T00:21:15.307367,2026-03-03T00:21:15.307367
10,14,GREENPOWER MOTOR Co INC.,None,1584547,LAUNCHED,F-1,2026-02-19,None,2026-03-03T00:21:14.055105,None,None,,https://www.sec.gov/Archives/edgar/data/1584547/00010629...,2026-03-03T00:20:43.853491,2026-03-03T00:21:14.060102
11,7,Elong Power Holding Ltd.,None,2015691,LAUNCHED,F-1,2026-02-17,None,2026-03-03T00:21:14.039162,None,None,,https://www.sec.gov/Archives/edgar/data/2015691/00014931...,2026-03-03T00:20:35.558040,2026-03-03T00:21:14.039162
12,26,Guardian Metal Resources PLC,None,2039972,FILED,F-1,2026-02-26,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2039972/00011046...,2026-03-03T00:21:10.208731,2026-03-03T00:21:10.208731
13,25,TRINITY BIOTECH PLC,None,888721,FILED,F-1,2026-02-25,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/888721/000117891...,2026-03-03T00:21:03.733262,2026-03-03T00:21:03.733262
14,24,Founder Group Ltd,None,1989930,FILED,F-1,2026-02-25,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1989930/00012139...,2026-03-03T00:21:02.141506,2026-03-03T00:21:02.141506
15,17,QUANTUM CORP /DE/,None,709283,LAUNCHED,S-1,2026-02-19,None,2026-03-03T00:20:59.093657,None,None,,https://www.sec.gov/Archives/edgar/data/709283/000162828...,2026-03-03T00:20:45.201780,2026-03-03T00:20:59.093657
16,23,Lantics Corp.,None,2112585,FILED,S-1,2026-02-24,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2112585/00016831...,2026-03-03T00:20:56.893533,2026-03-03T00:20:56.893533
17,22,Dune Acquisition Corp III,None,2095476,FILED,S-1,2026-02-24,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2095476/00012139...,2026-03-03T00:20:56.861665,2026-03-03T00:20:56.861665
18,21,K Wave Media Ltd.,None,2000756,FILED,F-1,2026-02-23,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2000756/00018291...,2026-03-03T00:20:52.164727,2026-03-03T00:20:52.164727
19,20,Yimutian Inc.,None,1991605,FILED,F-1,2026-02-23,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1991605/00012139...,2026-03-03T00:20:52.142667,2026-03-03T00:20:52.142667
20,19,Wearable Devices Ltd.,None,1887673,FILED,F-1,2026-02-23,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1887673/00012139...,2026-03-03T00:20:51.774554,2026-03-03T00:20:51.774554
21,6,SCHMID Group N.V.,None,1987240,LAUNCHED,F-1,2026-02-17,None,2026-03-03T00:20:49.030018,None,None,,https://www.sec.gov/Archives/edgar/data/1987240/00011046...,2026-03-03T00:20:35.329479,2026-03-03T00:20:49.030018
22,18,RWB Health Inc.,None,2107166,FILED,S-1,2026-02-20,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2107166/00014779...,2026-03-03T00:20:48.063808,2026-03-03T00:20:48.063808
23,16,Forefront Tech Holdings Acquisition Corp,None,2097986,FILED,S-1,2026-02-19,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2097986/00012139...,2026-03-03T00:20:44.905018,2026-03-03T00:20:44.905018
24,15,"Medical 21, Inc.",None,1673688,FILED,S-1,2026-02-19,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1673688/00012139...,2026-03-03T00:20:44.252920,2026-03-03T00:20:44.252920
25,13,NewHold Investment Corp IV,None,2099767,FILED,S-1,2026-02-18,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2099767/00012139...,2026-03-03T00:20:40.708103,2026-03-03T00:20:40.708103
26,12,Black Titan Corp,None,2034400,FILED,F-1,2026-02-18,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2034400/00014931...,2026-03-03T00:20:40.575839,2026-03-03T00:20:40.575839
27,11,RICHTECH ROBOTICS INC.,None,1963685,FILED,S-1,2026-02-18,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1963685/00012139...,2026-03-03T00:20:40.229808,2026-03-03T00:20:40.229808
28,10,CitroTech Inc.,None,894556,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/894556/000164033...,2026-03-03T00:20:36.552219,2026-03-03T00:20:36.552219
29,9,Dynamix Corp IV,None,2098142,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2098142/00012139...,2026-03-03T00:20:35.666623,2026-03-03T00:20:35.666623
30,8,Plutonian Acquisition Corp. II,None,2065661,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2065661/00014779...,2026-03-03T00:20:35.603934,2026-03-03T00:20:35.603934
31,5,"EIR Biopharma, Inc.",None,1966774,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1966774/00015201...,2026-03-03T00:20:35.298716,2026-03-03T00:20:35.298716
32,3,"DEEP FISSION, INC.",None,1918102,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1918102/00011046...,2026-03-03T00:20:34.765190,2026-03-03T00:20:34.765190
33,2,"Aspire Biopharma Holdings, Inc.",None,1847345,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1847345/00014931...,2026-03-03T00:20:34.725497,2026-03-03T00:20:34.725497
34,1,VEEA INC.,None,1840317,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1840317/00012139...,2026-03-03T00:20:34.709522,2026-03-03T00:20:34.709522

In [3]:
# Filter IPOs by status (change the status value as needed)
status_filter = "FILED"  # Options: FILED, AMENDED, PRICED, EFFECTIVE, LAUNCHED
df_ipos_filtered = pd.read_sql_query(
    "SELECT * FROM stock_ipos WHERE status = ? ORDER BY filing_date DESC",
    conn, params=[status_filter]
)
print(f"IPOs with status '{status_filter}': {len(df_ipos_filtered)}")
df_ipos_filtered

IPOs with status 'FILED': 30

,id,entity_name,ticker,cik,status,form_type,filing_date,effective_date,launch_date,price,exchange,sic_code,edgar_url,created_at,updated_at
0,27,"Modular Medical, Inc.",None,1074871,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1074871/00012139...,2026-03-03T00:21:15.307367,2026-03-03T00:21:15.307367
1,28,Steakholder Foods Ltd.,None,1828098,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1828098/00012139...,2026-03-03T00:21:22.405219,2026-03-03T00:21:22.405219
2,29,BeLive Holdings,None,1982448,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1982448/00014931...,2026-03-03T00:21:23.914265,2026-03-03T00:21:23.914265
3,30,Collab Z Inc.,None,2050338,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2050338/00012139...,2026-03-03T00:21:24.454667,2026-03-03T00:21:24.454667
4,31,TDE GROUP Ltd,None,2053475,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2053475/00018934...,2026-03-03T00:21:24.476671,2026-03-03T00:21:24.476671
5,32,APEX Global Solutions Ltd,None,2069858,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2069858/00012139...,2026-03-03T00:21:24.546673,2026-03-03T00:21:24.546673
6,33,Metals Royalty Co Inc.,None,2087398,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2087398/00011046...,2026-03-03T00:21:24.618340,2026-03-03T00:21:24.618340
7,34,UDynamics Ltd,None,2097903,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2097903/00012139...,2026-03-03T00:21:24.640312,2026-03-03T00:21:24.640312
8,35,RMG ML Sports Holdings,None,2104879,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2104879/00012139...,2026-03-03T00:21:24.695910,2026-03-03T00:21:24.695910
9,26,Guardian Metal Resources PLC,None,2039972,FILED,F-1,2026-02-26,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2039972/00011046...,2026-03-03T00:21:10.208731,2026-03-03T00:21:10.208731
10,24,Founder Group Ltd,None,1989930,FILED,F-1,2026-02-25,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1989930/00012139...,2026-03-03T00:21:02.141506,2026-03-03T00:21:02.141506
11,25,TRINITY BIOTECH PLC,None,888721,FILED,F-1,2026-02-25,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/888721/000117891...,2026-03-03T00:21:03.733262,2026-03-03T00:21:03.733262
12,22,Dune Acquisition Corp III,None,2095476,FILED,S-1,2026-02-24,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2095476/00012139...,2026-03-03T00:20:56.861665,2026-03-03T00:20:56.861665
13,23,Lantics Corp.,None,2112585,FILED,S-1,2026-02-24,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2112585/00016831...,2026-03-03T00:20:56.893533,2026-03-03T00:20:56.893533
14,19,Wearable Devices Ltd.,None,1887673,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1887673/00012139...,2026-03-03T00:20:51.774554,2026-03-03T00:20:51.774554
15,20,Yimutian Inc.,None,1991605,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1991605/00012139...,2026-03-03T00:20:52.142667,2026-03-03T00:20:52.142667
16,21,K Wave Media Ltd.,None,2000756,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2000756/00018291...,2026-03-03T00:20:52.164727,2026-03-03T00:20:52.164727
17,18,RWB Health Inc.,None,2107166,FILED,S-1,2026-02-20,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2107166/00014779...,2026-03-03T00:20:48.063808,2026-03-03T00:20:48.063808
18,15,"Medical 21, Inc.",None,1673688,FILED,S-1,2026-02-19,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1673688/00012139...,2026-03-03T00:20:44.252920,2026-03-03T00:20:44.252920
19,16,Forefront Tech Holdings Acquisition Corp,None,2097986,FILED,S-1,2026-02-19,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2097986/00012139...,2026-03-03T00:20:44.905018,2026-03-03T00:20:44.905018
20,11,RICHTECH ROBOTICS INC.,None,1963685,FILED,S-1,2026-02-18,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1963685/00012139...,2026-03-03T00:20:40.229808,2026-03-03T00:20:40.229808
21,12,Black Titan Corp,None,2034400,FILED,F-1,2026-02-18,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2034400/00014931...,2026-03-03T00:20:40.575839,2026-03-03T00:20:40.575839
22,13,NewHold Investment Corp IV,None,2099767,FILED,S-1,2026-02-18,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2099767/00012139...,2026-03-03T00:20:40.708103,2026-03-03T00:20:40.708103
23,1,VEEA INC.,None,1840317,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1840317/00012139...,2026-03-03T00:20:34.709522,2026-03-03T00:20:34.709522
24,2,"Aspire Biopharma Holdings, Inc.",None,1847345,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1847345/00014931...,2026-03-03T00:20:34.725497,2026-03-03T00:20:34.725497
25,3,"DEEP FISSION, INC.",None,1918102,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1918102/00011046...,2026-03-03T00:20:34.765190,2026-03-03T00:20:34.765190
26,5,"EIR Biopharma, Inc.",None,1966774,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1966774/00015201...,2026-03-03T00:20:35.298716,2026-03-03T00:20:35.298716
27,8,Plutonian Acquisition Corp. II,None,2065661,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2065661/00014779...,2026-03-03T00:20:35.603934,2026-03-03T00:20:35.603934
28,9,Dynamix Corp IV,None,2098142,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2098142/00012139...,2026-03-03T00:20:35.666623,2026-03-03T00:20:35.666623
29,10,CitroTech Inc.,None,894556,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/894556/000164033...,2026-03-03T00:20:36.552219,2026-03-03T00:20:36.552219

## ETF Launches Pipeline

All entities from N-1A and related filings, tracking from registration through launch.

In [4]:
# All ETF launches
df_etfs = pd.read_sql_query("SELECT * FROM etf_launches ORDER BY updated_at DESC", conn)
print(f"Total ETF entities: {len(df_etfs)}")
df_etfs

Total ETF entities: 0

Empty DataFrame
Columns: [id, fund_name, ticker, cik, status, form_type, filing_date, effective_date, launch_date, exchange, issuer, edgar_url, created_at, updated_at]
Index: []

In [5]:
# Filter ETFs by status
status_filter = "FILED"  # Options: FILED, AMENDED, PRICED, EFFECTIVE, LAUNCHED
df_etfs_filtered = pd.read_sql_query(
    "SELECT * FROM etf_launches WHERE status = ? ORDER BY filing_date DESC",
    conn, params=[status_filter]
)
print(f"ETFs with status '{status_filter}': {len(df_etfs_filtered)}")
df_etfs_filtered

ETFs with status 'FILED': 0

Empty DataFrame
Columns: [id, fund_name, ticker, cik, status, form_type, filing_date, effective_date, launch_date, exchange, issuer, edgar_url, created_at, updated_at]
Index: []

## Filing Events Log (Audit Trail)

Every individual SEC filing is recorded here. This is the raw event history — one row per filing document.

In [6]:
# Filing events with entity names
df_events = pd.read_sql_query("""
    SELECT
        fe.id,
        fe.entity_type,
        fe.entity_id,
        CASE
            WHEN fe.entity_type = 'IPO' THEN si.entity_name
            WHEN fe.entity_type = 'ETF' THEN el.fund_name
        END AS entity_name,
        fe.form_type,
        fe.filing_date,
        fe.accession_number,
        fe.description,
        fe.created_at
    FROM filing_events fe
    LEFT JOIN stock_ipos si ON fe.entity_type = 'IPO' AND fe.entity_id = si.id
    LEFT JOIN etf_launches el ON fe.entity_type = 'ETF' AND fe.entity_id = el.id
    ORDER BY fe.filing_date DESC
""", conn)
print(f"Total filing events: {len(df_events)}")
df_events

Total filing events: 43

,id,entity_type,entity_id,entity_name,form_type,filing_date,accession_number,description,created_at
0,33,IPO,27,"Modular Medical, Inc.",S-1,2026-02-27,0001213900-26-021221,"S-1 filing for Modular Medical, Inc.",2026-03-03T00:21:15.313366
1,34,IPO,28,Steakholder Foods Ltd.,F-1,2026-02-27,0001213900-26-021683,F-1 filing for Steakholder Foods Ltd.,2026-03-03T00:21:22.413221
2,35,IPO,4,SMX (Security Matters) Public Ltd Co,F-1/A,2026-02-27,0001493152-26-008355,F-1/A filing for SMX (Security Matters) Public Ltd Co,2026-03-03T00:21:22.992378
3,36,IPO,29,BeLive Holdings,F-1,2026-02-27,0001493152-26-008383,F-1 filing for BeLive Holdings,2026-03-03T00:21:23.924264
4,37,IPO,7,Elong Power Holding Ltd.,424B4,2026-02-27,0001493152-26-008271,424B4 filing for Elong Power Holding Ltd.,2026-03-03T00:21:24.277424
5,38,IPO,30,Collab Z Inc.,S-1,2026-02-27,0001213900-26-021753,S-1 filing for Collab Z Inc.,2026-03-03T00:21:24.460682
6,39,IPO,31,TDE GROUP Ltd,F-1,2026-02-27,0001893417-26-000005,F-1 filing for TDE GROUP Ltd,2026-03-03T00:21:24.481667
7,40,IPO,32,APEX Global Solutions Ltd,F-1,2026-02-27,0001213900-26-020913,F-1 filing for APEX Global Solutions Ltd,2026-03-03T00:21:24.552825
8,41,IPO,33,Metals Royalty Co Inc.,F-1,2026-02-27,0001104659-26-021062,F-1 filing for Metals Royalty Co Inc.,2026-03-03T00:21:24.624331
9,42,IPO,34,UDynamics Ltd,F-1,2026-02-27,0001213900-26-021223,F-1 filing for UDynamics Ltd,2026-03-03T00:21:24.646324
10,43,IPO,35,RMG ML Sports Holdings,S-1,2026-02-27,0001213900-26-021545,S-1 filing for RMG ML Sports Holdings,2026-03-03T00:21:24.702908
11,32,IPO,26,Guardian Metal Resources PLC,F-1,2026-02-26,0001104659-26-020524,F-1 filing for Guardian Metal Resources PLC,2026-03-03T00:21:10.213734
12,27,IPO,14,GREENPOWER MOTOR Co INC.,424B3,2026-02-25,0001062993-26-001164,424B3 filing for GREENPOWER MOTOR Co INC.,2026-03-03T00:21:01.058393
13,28,IPO,24,Founder Group Ltd,F-1,2026-02-25,0001213900-26-020337,F-1 filing for Founder Group Ltd,2026-03-03T00:21:02.147368
14,29,IPO,25,TRINITY BIOTECH PLC,F-1,2026-02-25,0001178913-26-000637,F-1 filing for TRINITY BIOTECH PLC,2026-03-03T00:21:03.745773
15,30,IPO,14,GREENPOWER MOTOR Co INC.,EFFECT,2026-02-25,9999999995-26-000668,EFFECT filing for GREENPOWER MOTOR Co INC.,2026-03-03T00:21:07.401639
16,31,IPO,7,Elong Power Holding Ltd.,EFFECT,2026-02-25,9999999995-26-000667,EFFECT filing for Elong Power Holding Ltd.,2026-03-03T00:21:10.190754
17,23,IPO,22,Dune Acquisition Corp III,S-1,2026-02-24,0001213900-26-019459,S-1 filing for Dune Acquisition Corp III,2026-03-03T00:20:56.868665
18,24,IPO,23,Lantics Corp.,S-1,2026-02-24,0001683168-26-001279,S-1 filing for Lantics Corp.,2026-03-03T00:20:56.898534
19,25,IPO,17,QUANTUM CORP /DE/,424B3,2026-02-24,0001628280-26-011100,424B3 filing for QUANTUM CORP /DE/,2026-03-03T00:20:57.440417
20,20,IPO,19,Wearable Devices Ltd.,F-1,2026-02-23,0001213900-26-019320,F-1 filing for Wearable Devices Ltd.,2026-03-03T00:20:51.783558
21,21,IPO,20,Yimutian Inc.,F-1,2026-02-23,0001213900-26-019317,F-1 filing for Yimutian Inc.,2026-03-03T00:20:52.147666
22,22,IPO,21,K Wave Media Ltd.,F-1,2026-02-23,0001829126-26-001570,F-1 filing for K Wave Media Ltd.,2026-03-03T00:20:52.169728
23,26,IPO,17,QUANTUM CORP /DE/,EFFECT,2026-02-23,9999999995-26-000653,EFFECT filing for QUANTUM CORP /DE/,2026-03-03T00:20:57.449424
24,19,IPO,18,RWB Health Inc.,S-1,2026-02-20,0001477932-26-000942,S-1 filing for RWB Health Inc.,2026-03-03T00:20:48.069706
25,14,IPO,14,GREENPOWER MOTOR Co INC.,F-1,2026-02-19,0001062993-26-001066,F-1 filing for GREENPOWER MOTOR Co INC.,2026-03-03T00:20:43.865493
26,15,IPO,15,"Medical 21, Inc.",S-1,2026-02-19,0001213900-26-018133,"S-1 filing for Medical 21, Inc.",2026-03-03T00:20:44.259922
27,16,IPO,16,Forefront Tech Holdings Acquisition Corp,S-1,2026-02-19,0001213900-26-018432,S-1 filing for Forefront Tech Holdings Acquisition Corp,2026-03-03T00:20:44.913028
28,17,IPO,17,QUANTUM CORP /DE/,S-1,2026-02-19,0001628280-26-009335,S-1 filing for QUANTUM CORP /DE/,2026-03-03T00:20:45.207779
29,18,IPO,6,SCHMID Group N.V.,EFFECT,2026-02-19,9999999995-26-000629,EFFECT filing for SCHMID Group N.V.,2026-03-03T00:20:47.654211
30,11,IPO,11,RICHTECH ROBOTICS INC.,S-1,2026-02-18,0001213900-26-017558,S-1 filing for RICHTECH ROBOTICS INC.,2026-03-03T00:20:40.237809
31,12,IPO,12,Black Titan Corp,F-1,2026-02-18,0001493152-26-007231,F-1 filing for Black Titan Corp,2026-03-03T00:20:40.583840
32,13,IPO,13,NewHold Investment Corp IV,S-1,2026-02-18,0001213900-26-018049,S-1 filing for NewHold Investment Corp IV,2026-03-03T00:20:40.714103
33,1,IPO,1,VEEA INC.,S-1,2026-02-17,0001213900-26-017472,S-1 filing for VEEA INC.,2026-03-03T00:20:34.717028
34,2,IPO,2,"Aspire Biopharma Holdings, Inc.",S-1,2026-02-17,0001493152-26-007123,"S-1 filing for Aspire Biopharma Holdings, Inc.",2026-03-03T00:20:34.729976
35,3,IPO,3,"DEEP FISSION, INC.",S-1,2026-02-17,0001104659-26-016226,"S-1 filing for DEEP FISSION, INC.",2026-03-03T00:20:34.771190
36,4,IPO,4,SMX (Security Matters) Public Ltd Co,F-1,2026-02-17,0001493152-26-007160,F-1 filing for SMX (Security Matters) Public Ltd Co,2026-03-03T00:20:34.818709
37,5,IPO,5,"EIR Biopharma, Inc.",S-1,2026-02-17,0001520138-26-000057,"S-1 filing for EIR Biopharma, Inc.",2026-03-03T00:20:35.307728
38,6,IPO,6,SCHMID Group N.V.,F-1,2026-02-17,0001104659-26-016336,F-1 filing for SCHMID Group N.V.,2026-03-03T00:20:35.333478
39,7,IPO,7,Elong Power Holding Ltd.,F-1,2026-02-17,0001493152-26-007179,F-1 filing for Elong Power Holding Ltd.,2026-03-03T00:20:35.566040
40,8,IPO,8,Plutonian Acquisition Corp. II,S-1,2026-02-17,0001477932-26-000869,S-1 filing for Plutonian Acquisition Corp. II,2026-03-03T00:20:35.609938
41,9,IPO,9,Dynamix Corp IV,S-1,2026-02-17,0001213900-26-017485,S-1 filing for Dynamix Corp IV,2026-03-03T00:20:35.673157
42,10,IPO,10,CitroTech Inc.,S-1,2026-02-17,0001640334-26-000331,S-1 filing for CitroTech Inc.,2026-03-03T00:20:36.561219

## Active Securities (Launched)

Entities that have been declared effective and moved to the action table.

In [7]:
# Active securities
df_active = pd.read_sql_query("SELECT * FROM active_securities ORDER BY created_at DESC", conn)
print(f"Total active securities: {len(df_active)}")
df_active

Total active securities: 4

   id entity_type               entity_name ticker                 launch_date  source_id                  created_at
0   4         IPO  GREENPOWER MOTOR Co INC.   None  2026-03-03T00:21:14.055105         14  2026-03-03T00:21:14.067102
1   3         IPO  Elong Power Holding Ltd.   None  2026-03-03T00:21:14.039162          7  2026-03-03T00:21:14.046705
2   2         IPO         QUANTUM CORP /DE/   None  2026-03-03T00:20:59.093657         17  2026-03-03T00:20:59.104166
3   1         IPO         SCHMID Group N.V.   None  2026-03-03T00:20:49.030018          6  2026-03-03T00:20:49.038024

## Notifications

Launch alerts. Unread notifications indicate newly launched securities you haven't reviewed yet.

In [8]:
# Unread notifications
df_notif = pd.read_sql_query(
    "SELECT * FROM notifications WHERE is_read = 0 ORDER BY created_at DESC", conn
)
print(f"Unread notifications: {len(df_notif)}")
df_notif

Unread notifications: 4

   id entity_type               entity_name ticker                                                      message  is_read                  created_at
0   4         IPO  GREENPOWER MOTOR Co INC.   None  🚀 IPO LAUNCHED: GREENPOWER MOTOR Co INC. has been declar...        0  2026-03-03T00:21:14.073533
1   3         IPO  Elong Power Holding Ltd.   None  🚀 IPO LAUNCHED: Elong Power Holding Ltd. has been declar...        0  2026-03-03T00:21:14.053103
2   2         IPO         QUANTUM CORP /DE/   None  🚀 IPO LAUNCHED: QUANTUM CORP /DE/ has been declared effe...        0  2026-03-03T00:20:59.110172
3   1         IPO         SCHMID Group N.V.   None  🚀 IPO LAUNCHED: SCHMID Group N.V. has been declared effe...        0  2026-03-03T00:20:49.046028

## Summary Statistics

Status distribution across all IPO and ETF entities.

In [9]:
# Status counts for IPOs and ETFs
print("=== Stock IPO Status Distribution ===")
df_ipo_status = pd.read_sql_query(
    "SELECT status, COUNT(*) as count FROM stock_ipos GROUP BY status ORDER BY count DESC", conn
)
print(df_ipo_status.to_string(index=False))

print("\n=== ETF Launch Status Distribution ===")
df_etf_status = pd.read_sql_query(
    "SELECT status, COUNT(*) as count FROM etf_launches GROUP BY status ORDER BY count DESC", conn
)
print(df_etf_status.to_string(index=False))

print(f"\n=== Totals ===")
print(f"IPO entities: {len(df_ipos) if 'df_ipos' in dir() else '(run IPO cell first)'}")
print(f"ETF entities: {len(df_etfs) if 'df_etfs' in dir() else '(run ETF cell first)'}")
print(f"Filing events: {conn.execute('SELECT COUNT(*) FROM filing_events').fetchone()[0]}")
print(f"Active securities: {conn.execute('SELECT COUNT(*) FROM active_securities').fetchone()[0]}")
print(f"Unread notifications: {conn.execute('SELECT COUNT(*) FROM notifications WHERE is_read=0').fetchone()[0]}")

=== Stock IPO Status Distribution ===
  status  count
   FILED     30
LAUNCHED      4
 AMENDED      1

=== ETF Launch Status Distribution ===
Empty DataFrame
Columns: [status, count]
Index: []

=== Totals ===
IPO entities: 35
ETF entities: 0
Filing events: 43
Active securities: 4
Unread notifications: 4

## Custom Query

Write your own SQL below to explore the data.

In [12]:
# Write your own SQL here
query = """
SELECT
    id,
    fund_name,
    form_type,
    filing_date,
    enriched_at,
    investment_theme,
    expense_ratio,
    fund_type,
    asset_class,
    portfolio_manager,
    benchmark_index,
    SUBSTR(principal_strategy, 1, 120) AS principal_strategy_preview
FROM etf_launches
ORDER BY enriched_at DESC NULLS LAST, updated_at DESC
"""
pd.read_sql_query(query, conn)

,id,fund_name,form_type,filing_date,enriched_at,investment_theme,expense_ratio,fund_type,asset_class,portfolio_manager,benchmark_index,principal_strategy_preview
0,1,American Drive Variable Insurance Trust,N-1A,2026-03-19,2026-04-30T21:47:27.105116,60/40 allocation strategy,None,Active,Multi-Asset,None,None,The Fund seeks to achieve its investment objective by in...