# IPO & ETF Launch Tracker — Data Explorer

Connect to the SQLite database and interactively explore all pipeline tables.  
Run cells top-to-bottom, or jump to any section you need.

In [2]:
import sqlite3
import pandas as pd
from pathlib import Path

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 60)
pd.set_option("display.width", 200)

# Connect to database
DB_PATH = Path("../db/ipo_etf_tracker.db")
assert DB_PATH.exists(), f"Database not found at {DB_PATH.resolve()}. Run 'python main.py --init' first."
conn = sqlite3.connect(str(DB_PATH))
print(f"Connected to {DB_PATH.resolve()}")

tables = [r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()]
print(f"Tables: {tables}")

Connected to C:\Users\vmc30\OneDrive\Desktop\Personal_Repos\IPO_ETF\db\ipo_etf_tracker.db
Tables: ['stock_ipos', 'sqlite_sequence', 'etf_launches', 'filing_events', 'active_securities', 'notifications']

## Stock IPOs Pipeline

All entities from S-1/F-1 filings, tracking from registration through launch.

In [3]:
# All stock IPOs
df_ipos = pd.read_sql_query("SELECT * FROM stock_ipos ORDER BY updated_at DESC", conn)
print(f"Total IPO entities: {len(df_ipos)}")
df_ipos

Total IPO entities: 355

,id,entity_name,ticker,cik,status,form_type,filing_date,effective_date,launch_date,price,exchange,sic_code,edgar_url,created_at,updated_at
0,350,"GUGGENHEIM DEFINED PORTFOLIOS, SERIES 2563",None,2102711,LAUNCHED,EFFECT,2026-02-26,None,2026-03-02T23:55:53.361324,None,None,,https://www.sec.gov/Archives/edgar/data/2102711/99999999...,2026-03-02T23:55:44.992276,2026-03-02T23:55:53.383326
1,335,SU Group Holdings Ltd,None,1969863,LAUNCHED,EFFECT,2026-02-26,None,2026-03-02T23:55:53.288979,None,None,,https://www.sec.gov/Archives/edgar/data/1969863/99999999...,2026-03-02T23:55:44.079078,2026-03-02T23:55:53.309826
2,332,Lavoro Ltd,None,1945711,LAUNCHED,EFFECT,2026-02-26,None,2026-03-02T23:55:53.219825,None,None,,https://www.sec.gov/Archives/edgar/data/1945711/99999999...,2026-03-02T23:55:43.784274,2026-03-02T23:55:53.240822
3,330,Gainbridge Life Insurance Co,None,1938470,LAUNCHED,EFFECT,2026-02-26,None,2026-03-02T23:55:53.154656,None,None,,https://www.sec.gov/Archives/edgar/data/1938470/99999999...,2026-03-02T23:55:43.752375,2026-03-02T23:55:53.174816
4,327,"Ping An Biomedical Co., Ltd.",None,1897532,LAUNCHED,EFFECT,2026-02-26,None,2026-03-02T23:55:53.082926,None,None,,https://www.sec.gov/Archives/edgar/data/1897532/99999999...,2026-03-02T23:55:43.541436,2026-03-02T23:55:53.109543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,59,Plutonian Acquisition Corp. II,None,2065661,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/2065661/00014779...,2026-03-02T23:54:32.276929,2026-03-02T23:54:32.276929
351,48,"EIR Biopharma, Inc.",None,1966774,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1966774/00015201...,2026-03-02T23:54:31.709213,2026-03-02T23:54:31.709213
352,42,"DEEP FISSION, INC.",None,1918102,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1918102/00011046...,2026-03-02T23:54:31.432595,2026-03-02T23:54:31.432595
353,36,"Aspire Biopharma Holdings, Inc.",None,1847345,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1847345/00014931...,2026-03-02T23:54:31.338052,2026-03-02T23:54:31.338052
354,35,VEEA INC.,None,1840317,FILED,S-1,2026-02-17,None,NaN,None,None,,https://www.sec.gov/Archives/edgar/data/1840317/00012139...,2026-03-02T23:54:31.325052,2026-03-02T23:54:31.325052

In [4]:
# Filter IPOs by status (change the status value as needed)
status_filter = "FILED"  # Options: FILED, AMENDED, PRICED, EFFECTIVE, LAUNCHED
df_ipos_filtered = pd.read_sql_query(
    "SELECT * FROM stock_ipos WHERE status = ? ORDER BY filing_date DESC",
    conn, params=[status_filter]
)
print(f"IPOs with status '{status_filter}': {len(df_ipos_filtered)}")
df_ipos_filtered

IPOs with status 'FILED': 29

,id,entity_name,ticker,cik,status,form_type,filing_date,effective_date,launch_date,price,exchange,sic_code,edgar_url,created_at,updated_at
0,314,"Modular Medical, Inc.",None,1074871,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1074871/00012139...,2026-03-02T23:55:35.309678,2026-03-02T23:55:35.309678
1,322,Steakholder Foods Ltd.,None,1828098,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1828098/00012139...,2026-03-02T23:55:43.071975,2026-03-02T23:55:43.071975
2,336,BeLive Holdings,None,1982448,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1982448/00014931...,2026-03-02T23:55:44.175088,2026-03-02T23:55:44.175088
3,340,Collab Z Inc.,None,2050338,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2050338/00012139...,2026-03-02T23:55:44.746211,2026-03-02T23:55:44.746211
4,342,TDE GROUP Ltd,None,2053475,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2053475/00018934...,2026-03-02T23:55:44.767431,2026-03-02T23:55:44.767431
5,344,APEX Global Solutions Ltd,None,2069858,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2069858/00012139...,2026-03-02T23:55:44.837004,2026-03-02T23:55:44.837004
6,347,Metals Royalty Co Inc.,None,2087398,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2087398/00011046...,2026-03-02T23:55:44.909938,2026-03-02T23:55:44.909938
7,348,UDynamics Ltd,None,2097903,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2097903/00012139...,2026-03-02T23:55:44.927053,2026-03-02T23:55:44.927053
8,351,RMG ML Sports Holdings,None,2104879,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2104879/00012139...,2026-03-02T23:55:45.005283,2026-03-02T23:55:45.005283
9,307,Guardian Metal Resources PLC,None,2039972,FILED,F-1,2026-02-26,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2039972/00011046...,2026-03-02T23:55:27.096015,2026-03-02T23:55:27.096015
10,283,Founder Group Ltd,None,1989930,FILED,F-1,2026-02-25,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1989930/00012139...,2026-03-02T23:55:15.551385,2026-03-02T23:55:15.551385
11,260,Dune Acquisition Corp III,None,2095476,FILED,S-1,2026-02-24,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2095476/00012139...,2026-03-02T23:55:07.870469,2026-03-02T23:55:07.870469
12,262,Lantics Corp.,None,2112585,FILED,S-1,2026-02-24,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2112585/00016831...,2026-03-02T23:55:07.929075,2026-03-02T23:55:07.929075
13,219,Wearable Devices Ltd.,None,1887673,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1887673/00012139...,2026-03-02T23:55:01.310215,2026-03-02T23:55:01.310215
14,222,Yimutian Inc.,None,1991605,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1991605/00012139...,2026-03-02T23:55:01.501562,2026-03-02T23:55:01.501562
15,224,K Wave Media Ltd.,None,2000756,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2000756/00018291...,2026-03-02T23:55:01.533981,2026-03-02T23:55:01.533981
16,198,RWB Health Inc.,None,2107166,FILED,S-1,2026-02-20,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2107166/00014779...,2026-03-02T23:54:55.703904,2026-03-02T23:54:55.703904
17,145,"Medical 21, Inc.",None,1673688,FILED,S-1,2026-02-19,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1673688/00012139...,2026-03-02T23:54:48.618176,2026-03-02T23:54:48.618176
18,159,Forefront Tech Holdings Acquisition Corp,None,2097986,FILED,S-1,2026-02-19,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2097986/00012139...,2026-03-02T23:54:49.568163,2026-03-02T23:54:49.568163
19,118,RICHTECH ROBOTICS INC.,None,1963685,FILED,S-1,2026-02-18,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1963685/00012139...,2026-03-02T23:54:41.434331,2026-03-02T23:54:41.434331
20,121,Black Titan Corp,None,2034400,FILED,F-1,2026-02-18,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2034400/00014931...,2026-03-02T23:54:41.984491,2026-03-02T23:54:41.984491
21,131,NewHold Investment Corp IV,None,2099767,FILED,S-1,2026-02-18,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2099767/00012139...,2026-03-02T23:54:42.229073,2026-03-02T23:54:42.229073
22,35,VEEA INC.,None,1840317,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1840317/00012139...,2026-03-02T23:54:31.325052,2026-03-02T23:54:31.325052
23,36,"Aspire Biopharma Holdings, Inc.",None,1847345,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1847345/00014931...,2026-03-02T23:54:31.338052,2026-03-02T23:54:31.338052
24,42,"DEEP FISSION, INC.",None,1918102,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1918102/00011046...,2026-03-02T23:54:31.432595,2026-03-02T23:54:31.432595
25,48,"EIR Biopharma, Inc.",None,1966774,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1966774/00015201...,2026-03-02T23:54:31.709213,2026-03-02T23:54:31.709213
26,59,Plutonian Acquisition Corp. II,None,2065661,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2065661/00014779...,2026-03-02T23:54:32.276929,2026-03-02T23:54:32.276929
27,68,Dynamix Corp IV,None,2098142,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2098142/00012139...,2026-03-02T23:54:32.431829,2026-03-02T23:54:32.431829
28,87,CitroTech Inc.,None,894556,FILED,S-1,2026-02-17,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/894556/000164033...,2026-03-02T23:54:33.451251,2026-03-02T23:54:33.451251

## ETF Launches Pipeline

All entities from N-1A and related filings, tracking from registration through launch.

In [5]:
# All ETF launches
df_etfs = pd.read_sql_query("SELECT * FROM etf_launches ORDER BY updated_at DESC", conn)
print(f"Total ETF entities: {len(df_etfs)}")
df_etfs

Total ETF entities: 566

,id,fund_name,ticker,cik,status,form_type,filing_date,effective_date,launch_date,exchange,issuer,edgar_url,created_at,updated_at
0,566,CREDIT SUISSE OPPORTUNITY FUNDS,None,946110,LAUNCHED,485BPOS,2026-02-27,None,2026-03-02T23:55:56.324826,None,None,https://www.sec.gov/Archives/edgar/data/946110/000110465...,2026-03-02T23:55:50.884194,2026-03-02T23:55:56.334840
1,563,ALGER FUNDS II,None,92751,LAUNCHED,485BPOS,2026-02-27,None,2026-03-02T23:55:56.290512,None,None,https://www.sec.gov/Archives/edgar/data/92751/0001193125...,2026-03-02T23:55:50.666928,2026-03-02T23:55:56.299505
2,561,Investment Managers Series Trust III,None,924727,LAUNCHED,485BPOS,2026-02-27,None,2026-03-02T23:55:56.260817,None,None,https://www.sec.gov/Archives/edgar/data/924727/000121390...,2026-03-02T23:55:50.632399,2026-03-02T23:55:56.267823
3,556,FINANCIAL INVESTORS TRUST,None,915802,LAUNCHED,485BPOS,2026-02-27,None,2026-03-02T23:55:56.231406,None,None,https://www.sec.gov/Archives/edgar/data/915802/000139834...,2026-03-02T23:55:50.440411,2026-03-02T23:55:56.239922
4,555,"NICHOLAS EQUITY INCOME FUND, INC.",None,913131,LAUNCHED,485BPOS,2026-02-27,None,2026-03-02T23:55:56.202743,None,None,https://www.sec.gov/Archives/edgar/data/913131/000119312...,2026-03-02T23:55:50.416023,2026-03-02T23:55:56.211386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,6,BNY MELLON FUNDS TRUST,None,1111565,PRICED,497,2026-02-17,None,NaN,None,None,https://www.sec.gov/Archives/edgar/data/1111565/00000301...,2026-03-02T23:54:28.678010,2026-03-02T23:54:34.635236
562,5,Voya EQUITY TRUST,None,1063946,PRICED,497,2026-02-17,None,NaN,None,None,https://www.sec.gov/Archives/edgar/data/1063946/00011931...,2026-03-02T23:54:28.655093,2026-03-02T23:54:34.628236
563,3,Voya PARTNERS INC,None,1039001,PRICED,497K,2026-02-17,None,NaN,None,None,https://www.sec.gov/Archives/edgar/data/1039001/00011931...,2026-03-02T23:54:28.572697,2026-03-02T23:54:34.614046
564,2,EQ ADVISORS TRUST,None,1027263,PRICED,497K,2026-02-17,None,NaN,None,None,https://www.sec.gov/Archives/edgar/data/1027263/00011931...,2026-03-02T23:54:28.528309,2026-03-02T23:54:34.607051
565,1,LITMAN GREGORY FUNDS TRUST,None,1020425,PRICED,497,2026-02-17,None,NaN,None,None,https://www.sec.gov/Archives/edgar/data/1020425/00011931...,2026-03-02T23:54:28.515310,2026-03-02T23:54:34.600045

In [6]:
# Filter ETFs by status
status_filter = "FILED"  # Options: FILED, AMENDED, PRICED, EFFECTIVE, LAUNCHED
df_etfs_filtered = pd.read_sql_query(
    "SELECT * FROM etf_launches WHERE status = ? ORDER BY filing_date DESC",
    conn, params=[status_filter]
)
print(f"ETFs with status '{status_filter}': {len(df_etfs_filtered)}")
df_etfs_filtered

ETFs with status 'FILED': 0

Empty DataFrame
Columns: [id, fund_name, ticker, cik, status, form_type, filing_date, effective_date, launch_date, exchange, issuer, edgar_url, created_at, updated_at]
Index: []

## Filing Events Log (Audit Trail)

Every individual SEC filing is recorded here. This is the raw event history — one row per filing document.

In [7]:
# Filing events with entity names
df_events = pd.read_sql_query("""
    SELECT
        fe.id,
        fe.entity_type,
        fe.entity_id,
        CASE
            WHEN fe.entity_type = 'IPO' THEN si.entity_name
            WHEN fe.entity_type = 'ETF' THEN el.fund_name
        END AS entity_name,
        fe.form_type,
        fe.filing_date,
        fe.accession_number,
        fe.description,
        fe.created_at
    FROM filing_events fe
    LEFT JOIN stock_ipos si ON fe.entity_type = 'IPO' AND fe.entity_id = si.id
    LEFT JOIN etf_launches el ON fe.entity_type = 'ETF' AND fe.entity_id = el.id
    ORDER BY fe.filing_date DESC
""", conn)
print(f"Total filing events: {len(df_events)}")
df_events

Total filing events: 8536

        id entity_type  entity_id                  entity_name form_type filing_date      accession_number                                     description                  created_at
0     5974         IPO          1         ROYAL BANK OF CANADA     424B2  2026-02-27  0000950103-26-002791           424B2 filing for ROYAL BANK OF CANADA  2026-03-02T23:55:34.058682
1     5975         IPO          1         ROYAL BANK OF CANADA     424B2  2026-02-27  0000950103-26-002806           424B2 filing for ROYAL BANK OF CANADA  2026-03-02T23:55:34.067685
2     5976         IPO          1         ROYAL BANK OF CANADA     424B2  2026-02-27  0000950103-26-002807           424B2 filing for ROYAL BANK OF CANADA  2026-03-02T23:55:34.073684
3     5977         IPO          1         ROYAL BANK OF CANADA     424B2  2026-02-27  0000950103-26-002809           424B2 filing for ROYAL BANK OF CANADA  2026-03-02T23:55:34.080960
4     5978         IPO          1         ROYAL BANK OF CANADA     424B2  2026-02-27  0000950103-26-002823           424B2 filing for ROYAL BANK OF CANADA  2026-03-02T23:55:34.086984
...    ...         ...        ...                          ...       ...         ...                   ...                                             ...                         ...
8531   510         IPO         78           Smart Powerr Corp.    EFFECT  2026-02-13  9999999995-26-000574            EFFECT filing for Smart Powerr Corp.  2026-03-02T23:54:32.930672
8532   517         IPO         80      PRUCO LIFE INSURANCE CO    EFFECT  2026-02-13  9999999995-26-000570       EFFECT filing for PRUCO LIFE INSURANCE CO  2026-03-02T23:54:32.990507
8533   520         IPO         81       Cardiff Lexington Corp    EFFECT  2026-02-13  9999999995-26-000571        EFFECT filing for Cardiff Lexington Corp  2026-03-02T23:54:33.027487
8534  6393         ETF        237  Manager Directed Portfolios   485APOS  2024-05-31  0000894189-24-003479  485APOS filing for Manager Directed Portfolios  2026-03-02T23:55:36.915608
8535  7349         ETF         18      ETF Opportunities Trust   485APOS  2023-10-25  0001387131-23-012643      485APOS filing for ETF Opportunities Trust  2026-03-02T23:55:42.683847

[8536 rows x 9 columns]

## Active Securities (Launched)

Entities that have been declared effective and moved to the action table.

In [8]:
# Active securities
df_active = pd.read_sql_query("SELECT * FROM active_securities ORDER BY created_at DESC", conn)
print(f"Total active securities: {len(df_active)}")
df_active

Total active securities: 459

      id entity_type                             entity_name ticker                 launch_date  source_id                  created_at
0    459         ETF         CREDIT SUISSE OPPORTUNITY FUNDS   None  2026-03-02T23:55:56.324826        566  2026-03-02T23:55:56.345396
1    458         ETF                          ALGER FUNDS II   None  2026-03-02T23:55:56.290512        563  2026-03-02T23:55:56.311033
2    457         ETF    Investment Managers Series Trust III   None  2026-03-02T23:55:56.260817        561  2026-03-02T23:55:56.278742
3    456         ETF               FINANCIAL INVESTORS TRUST   None  2026-03-02T23:55:56.231406        556  2026-03-02T23:55:56.250945
4    455         ETF       NICHOLAS EQUITY INCOME FUND, INC.   None  2026-03-02T23:55:56.202743        555  2026-03-02T23:55:56.221393
..   ...         ...                                     ...    ...                         ...        ...                         ...
454    5         IPO  Rocky Mountain Chocolate Factory, Inc.   None  2026-03-02T23:54:34.990926         15  2026-03-02T23:54:35.006926
455    4         IPO              Northern Lights Fund Trust   None  2026-03-02T23:54:34.964417         11  2026-03-02T23:54:34.979925
456    3         IPO           SOUTHERN FIRST BANCSHARES INC   None  2026-03-02T23:54:34.942413          5  2026-03-02T23:54:34.957417
457    2         IPO               DYNAVAX TECHNOLOGIES CORP   None  2026-03-02T23:54:34.916413          3  2026-03-02T23:54:34.932414
458    1         IPO              AVADEL PHARMACEUTICALS PLC   None  2026-03-02T23:54:34.900128          2  2026-03-02T23:54:34.908127

[459 rows x 7 columns]

## Notifications

Launch alerts. Unread notifications indicate newly launched securities you haven't reviewed yet.

In [9]:
# Unread notifications
df_notif = pd.read_sql_query(
    "SELECT * FROM notifications WHERE is_read = 0 ORDER BY created_at DESC", conn
)
print(f"Unread notifications: {len(df_notif)}")
df_notif

Unread notifications: 459

      id entity_type                             entity_name ticker                                                      message  is_read                  created_at
0    459         ETF         CREDIT SUISSE OPPORTUNITY FUNDS   None  🚀 ETF LAUNCHED: CREDIT SUISSE OPPORTUNITY FUNDS has been...        0  2026-03-02T23:55:56.355393
1    458         ETF                          ALGER FUNDS II   None  🚀 ETF LAUNCHED: ALGER FUNDS II has been declared effecti...        0  2026-03-02T23:55:56.322826
2    457         ETF    Investment Managers Series Trust III   None  🚀 ETF LAUNCHED: Investment Managers Series Trust III has...        0  2026-03-02T23:55:56.289495
3    456         ETF               FINANCIAL INVESTORS TRUST   None  🚀 ETF LAUNCHED: FINANCIAL INVESTORS TRUST has been decla...        0  2026-03-02T23:55:56.259380
4    455         ETF       NICHOLAS EQUITY INCOME FUND, INC.   None  🚀 ETF LAUNCHED: NICHOLAS EQUITY INCOME FUND, INC. has be...        0  2026-03-02T23:55:56.230407
..   ...         ...                                     ...    ...                                                          ...      ...                         ...
454    5         IPO  Rocky Mountain Chocolate Factory, Inc.   None  🚀 IPO LAUNCHED: Rocky Mountain Chocolate Factory, Inc. h...        0  2026-03-02T23:54:35.014925
455    4         IPO              Northern Lights Fund Trust   None  🚀 IPO LAUNCHED: Northern Lights Fund Trust has been decl...        0  2026-03-02T23:54:34.988925
456    3         IPO           SOUTHERN FIRST BANCSHARES INC   None  🚀 IPO LAUNCHED: SOUTHERN FIRST BANCSHARES INC has been d...        0  2026-03-02T23:54:34.963418
457    2         IPO               DYNAVAX TECHNOLOGIES CORP   None  🚀 IPO LAUNCHED: DYNAVAX TECHNOLOGIES CORP has been decla...        0  2026-03-02T23:54:34.941413
458    1         IPO              AVADEL PHARMACEUTICALS PLC   None  🚀 IPO LAUNCHED: AVADEL PHARMACEUTICALS PLC has been decl...        0  2026-03-02T23:54:34.915413

[459 rows x 7 columns]

## Summary Statistics

Status distribution across all IPO and ETF entities.

In [10]:
# Status counts for IPOs and ETFs
print("=== Stock IPO Status Distribution ===")
df_ipo_status = pd.read_sql_query(
    "SELECT status, COUNT(*) as count FROM stock_ipos GROUP BY status ORDER BY count DESC", conn
)
print(df_ipo_status.to_string(index=False))

print("\n=== ETF Launch Status Distribution ===")
df_etf_status = pd.read_sql_query(
    "SELECT status, COUNT(*) as count FROM etf_launches GROUP BY status ORDER BY count DESC", conn
)
print(df_etf_status.to_string(index=False))

print(f"\n=== Totals ===")
print(f"IPO entities: {len(df_ipos) if 'df_ipos' in dir() else '(run IPO cell first)'}")
print(f"ETF entities: {len(df_etfs) if 'df_etfs' in dir() else '(run ETF cell first)'}")
print(f"Filing events: {conn.execute('SELECT COUNT(*) FROM filing_events').fetchone()[0]}")
print(f"Active securities: {conn.execute('SELECT COUNT(*) FROM active_securities').fetchone()[0]}")
print(f"Unread notifications: {conn.execute('SELECT COUNT(*) FROM notifications WHERE is_read=0').fetchone()[0]}")

=== Stock IPO Status Distribution ===
  status  count
  PRICED    165
LAUNCHED    111
 AMENDED     50
   FILED     29

=== ETF Launch Status Distribution ===
  status  count
LAUNCHED    348
  PRICED    186
 AMENDED     32

=== Totals ===
IPO entities: 355
ETF entities: 566
Filing events: 8536
Active securities: 459
Unread notifications: 459

## Custom Query

Write your own SQL below to explore the data.

In [11]:
# Write your own SQL here
query = """
SELECT * FROM stock_ipos
WHERE status = 'FILED'
ORDER BY filing_date DESC
LIMIT 20
"""
pd.read_sql_query(query, conn)

,id,entity_name,ticker,cik,status,form_type,filing_date,effective_date,launch_date,price,exchange,sic_code,edgar_url,created_at,updated_at
0,314,"Modular Medical, Inc.",None,1074871,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1074871/00012139...,2026-03-02T23:55:35.309678,2026-03-02T23:55:35.309678
1,322,Steakholder Foods Ltd.,None,1828098,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1828098/00012139...,2026-03-02T23:55:43.071975,2026-03-02T23:55:43.071975
2,336,BeLive Holdings,None,1982448,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1982448/00014931...,2026-03-02T23:55:44.175088,2026-03-02T23:55:44.175088
3,340,Collab Z Inc.,None,2050338,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2050338/00012139...,2026-03-02T23:55:44.746211,2026-03-02T23:55:44.746211
4,342,TDE GROUP Ltd,None,2053475,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2053475/00018934...,2026-03-02T23:55:44.767431,2026-03-02T23:55:44.767431
5,344,APEX Global Solutions Ltd,None,2069858,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2069858/00012139...,2026-03-02T23:55:44.837004,2026-03-02T23:55:44.837004
6,347,Metals Royalty Co Inc.,None,2087398,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2087398/00011046...,2026-03-02T23:55:44.909938,2026-03-02T23:55:44.909938
7,348,UDynamics Ltd,None,2097903,FILED,F-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2097903/00012139...,2026-03-02T23:55:44.927053,2026-03-02T23:55:44.927053
8,351,RMG ML Sports Holdings,None,2104879,FILED,S-1,2026-02-27,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2104879/00012139...,2026-03-02T23:55:45.005283,2026-03-02T23:55:45.005283
9,307,Guardian Metal Resources PLC,None,2039972,FILED,F-1,2026-02-26,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2039972/00011046...,2026-03-02T23:55:27.096015,2026-03-02T23:55:27.096015
10,283,Founder Group Ltd,None,1989930,FILED,F-1,2026-02-25,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1989930/00012139...,2026-03-02T23:55:15.551385,2026-03-02T23:55:15.551385
11,260,Dune Acquisition Corp III,None,2095476,FILED,S-1,2026-02-24,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2095476/00012139...,2026-03-02T23:55:07.870469,2026-03-02T23:55:07.870469
12,262,Lantics Corp.,None,2112585,FILED,S-1,2026-02-24,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2112585/00016831...,2026-03-02T23:55:07.929075,2026-03-02T23:55:07.929075
13,219,Wearable Devices Ltd.,None,1887673,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1887673/00012139...,2026-03-02T23:55:01.310215,2026-03-02T23:55:01.310215
14,222,Yimutian Inc.,None,1991605,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1991605/00012139...,2026-03-02T23:55:01.501562,2026-03-02T23:55:01.501562
15,224,K Wave Media Ltd.,None,2000756,FILED,F-1,2026-02-23,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2000756/00018291...,2026-03-02T23:55:01.533981,2026-03-02T23:55:01.533981
16,198,RWB Health Inc.,None,2107166,FILED,S-1,2026-02-20,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2107166/00014779...,2026-03-02T23:54:55.703904,2026-03-02T23:54:55.703904
17,145,"Medical 21, Inc.",None,1673688,FILED,S-1,2026-02-19,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1673688/00012139...,2026-03-02T23:54:48.618176,2026-03-02T23:54:48.618176
18,159,Forefront Tech Holdings Acquisition Corp,None,2097986,FILED,S-1,2026-02-19,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/2097986/00012139...,2026-03-02T23:54:49.568163,2026-03-02T23:54:49.568163
19,118,RICHTECH ROBOTICS INC.,None,1963685,FILED,S-1,2026-02-18,None,None,None,None,,https://www.sec.gov/Archives/edgar/data/1963685/00012139...,2026-03-02T23:54:41.434331,2026-03-02T23:54:41.434331